
name: Node.js CI

on:
  push:
    branches: [ development, linus, johan, farzane, tina, elias, dennis, madde ]
  pull_request:
    branches: [ staging, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/sis

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
    
  development:
    if: github.event_name == 'push'|github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
    - run: echo ${{ secrets.TESTNYCKEL }}
    
  staging:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/development'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
      
  deploy:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: master
      url: xx
    steps:
      - name: deploy
        run: echo "deploying"
        env:
          CI: false
